# Generated by Django 4.2.1 on 2023-09-07 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appointmentio", "0003_treatedcondition_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accountio", "0003_prescriptionadditionalconnector_primary_disease_and_more"),
        ("threadio", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inbox",
            unique_together={("thread", "user", "organization")},
        ),
        migrations.AlterIndexTogether(
            name="inbox",
            index_together={("thread", "user", "organization")},
        ),
        migrations.AddField(
            model_name="thread",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="appointmentio.appointment",
            ),
        ),
        migrations.RemoveField(
            model_name="inbox",
            name="appointment",
        ),
    ]
