# Generated by Django 4.2.1 on 2023-08-21 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("addressio", "0001_initial"),
        ("appointmentio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accountio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliation",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accountio.organization",
            ),
        ),
        migrations.AddField(
            model_name="descendant",
            name="child",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_set",
                to="accountio.organization",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="descendant",
            name="parent",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="descendant_set",
                to="accountio.organization",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalorganization",
            name="address",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="addressio.address",
            ),
        ),
        migrations.AddField(
            model_name="historicalorganization",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalorganization",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accountio.organization",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="addressio.address",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="accountio.organization",
            ),
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accountio.organization",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="referrer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accountio.organizationuser",
            ),
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prescriptionadditionalconnector",
            name="prescription",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="appointmentio.prescription",
            ),
            preserve_default=False,
        ),
    ]
