# Generated by Django 4.2.1 on 2023-08-21 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patientio", "0001_initial"),
        ("doctorio", "0001_initial"),
        ("accountio", "0002_affiliation_organization_descendant_child_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appointmentio", "0002_appointment_creator_user_appointment_doctor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionadditionalconnector",
            name="primary_disease",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="patientio.primarydisease",
            ),
        ),
        migrations.AddField(
            model_name="prescriptionadditionalconnector",
            name="recommendation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="doctorio.recommendations",
            ),
        ),
        migrations.AddField(
            model_name="prescriptionadditionalconnector",
            name="treatment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="appointmentio.prescriptionmedicineconnector",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="descendant",
            unique_together={("parent", "child")},
        ),
        migrations.AlterUniqueTogether(
            name="organizationuser",
            unique_together={("organization", "user")},
        ),
    ]
