# Generated by Django 4.2.1 on 2023-08-21 13:02

import autoslug.fields
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import notificationio.utils
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patientio", "0001_initial"),
        ("doctorio", "0001_initial"),
        ("accountio", "0002_affiliation_organization_descendant_child_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appointmentio", "0002_appointment_creator_user_appointment_doctor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=notificationio.utils.get_notification_slug,
                        unique=True,
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("ORGANIZATION", "Organization"),
                            ("DOCTOR", "Doctor"),
                            ("PATIENT", "Patient"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PASSWORD_CHANGED", "Password Changed"),
                            ("INCOMPLETE_PROFILE", "Incomplete Profile"),
                            ("APPOINTMENT_REQUESTED", "Appointment Requested"),
                            ("APPOINTMENT_SCHEDULED", "Appointment Scheduled"),
                            ("APPOINTMENT_COMPLETED", "Appointment Completed"),
                            ("APPOINTMENT_CANCELED", "Appointment Canceled"),
                            ("APPOINTMENT_REMOVED", "Appointment Removed"),
                            ("APPOINTMENT_REMINDER", "Appointment Reminder"),
                            ("APPOINTMENT_STARTED", "Appointment Started"),
                            ("SCHEDULE_TIME_UPDATED", "Schedule Time Updated"),
                            ("PRESCRIPTION_CREATED", "Prescription Created"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_unread", models.BooleanField(default=True)),
                (
                    "model_kind",
                    models.CharField(
                        choices=[
                            ("ORGANIZATION", "Organization"),
                            ("DOCTOR", "Doctor"),
                            ("PATIENT", "Patient"),
                            ("APPOINTMENT", "Appointment"),
                            ("PRESCRIPTION", "Prescription"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointmentio.appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctorio.doctor",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountio.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patientio.patient",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointmentio.prescription",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiver_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
