# Generated by Django 4.2.1 on 2023-09-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notificationio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("REMOVED", "Removed")],
                default="ACTIVE",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("PASSWORD_CHANGED", "Password Changed"),
                    ("INCOMPLETE_PROFILE", "Incomplete Profile"),
                    ("APPOINTMENT_REQUESTED", "Appointment Requested"),
                    ("APPOINTMENT_SCHEDULED", "Appointment Scheduled"),
                    ("APPOINTMENT_COMPLETED", "Appointment Completed"),
                    ("APPOINTMENT_CANCELED", "Appointment Canceled"),
                    ("APPOINTMENT_REMOVED", "Appointment Removed"),
                    ("APPOINTMENT_REMINDER", "Appointment Reminder"),
                    ("APPOINTMENT_STARTED", "Appointment Started"),
                    ("SCHEDULE_TIME_UPDATED", "Schedule Time Updated"),
                    ("PRESCRIPTION_CREATED", "Prescription Created"),
                    ("JOINED_VIDEO_CALL", "Joined Video Call"),
                ],
                max_length=30,
            ),
        ),
    ]
