# Generated by Django 4.2.1 on 2023-08-21 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("addressio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="addressconnector",
            name="address",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="addressio.address",
            ),
            preserve_default=False,
        ),
    ]
