# Generated by Django 4.2.1 on 2023-08-21 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patientio", "0001_initial"),
        ("doctorio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accountio", "0002_affiliation_organization_descendant_child_and_more"),
        ("addressio", "0002_addressconnector_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="addressconnector",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="doctorio.doctor",
            ),
        ),
        migrations.AddField(
            model_name="addressconnector",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accountio.organization",
            ),
        ),
        migrations.AddField(
            model_name="addressconnector",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="patientio.patient",
            ),
        ),
        migrations.AddField(
            model_name="historicaladdress",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaladdressconnector",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="doctorio.doctor",
            ),
        ),
        migrations.AddField(
            model_name="historicaladdressconnector",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaladdressconnector",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accountio.organization",
            ),
        ),
        migrations.AddField(
            model_name="historicaladdressconnector",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="patientio.patient",
            ),
        ),
    ]
